/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "STD_TYPES.h"
#include "MCAL_RCC_Interface.h"
#include "MCAL_RCC_Private.h"

#include "MCAL_GPIO_Interface.h"
#include "MCAL_GPIO_Config.h"


#include "MCAL_STK_Interface.h"
#include "SRV_RTO_Interface.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void App_LED1();
void App_LED2();
void App_LED3();

int main(void)
{
	MCL_GPIO_vSetPinCfg(LED_Port, LED1_Pin, &GPIO_LED_Config);
	MCL_GPIO_vSetPinCfg(LED_Port, LED2_Pin, &GPIO_LED_Config);
	MCL_GPIO_vSetPinCfg(LED_Port, LED3_Pin, &GPIO_LED_Config);
  /* Step 3 :Create 3 Tasks */
  SRV_RTO_vCreateTask(0, 1000, 0, &App_LED1);
  SRV_RTO_vCreateTask(1, 2000, 100, &App_LED2);
  SRV_RTO_vCreateTask(2, 3000, 200, &App_LED3);

  /* Step 5 : Wait forever */
  /* Initialize System */
  SRV_RTO_vStartOS();
	for(;;);
}


void App_LED1()
{
  MCL_GPIO_vTogglePin(LED_Port, LED1_Pin);
}
void App_LED2()
{
  MCL_GPIO_vTogglePin(LED_Port, LED2_Pin);
}
void App_LED3()
{
  MCL_GPIO_vTogglePin(LED_Port, LED3_Pin);
}
